const $ = (selector) => document.querySelector(selector);
let activeId = null;
let config = null;
let settings = null;
let language = "zh";
let lastRunSignature = null;
let selectedWorkdir = null;
let editingMcpName = null;
const openStepDetails = new Set();

const text = {
  zh: {newTopic:"新建话题",history:"过往话题",settings:"设置",settingsHint:"权限、模型与扩展",guide:"使用指南",guideHint:"第一次使用先看这里",welcomeTitle:"把目标告诉我，剩下的交给 ClearAct",welcomeHint:"你不需要先选择工具。直接描述想完成的事情，我会根据任务自动使用文件、网页和已接入的 MCP 能力。",exampleFiles:"处理本地文件",exampleFilesHint:"选择文件夹后读取、分析或生成文件",exampleMcp:"接入新能力",exampleMcpHint:"选择连接方式，ClearAct 完成配置",openGuide:"查看完整使用指南",guideStep1:"先描述目标",guideStep1Text:"在底部输入框用自然语言说清楚要完成什么。",guideStep2:"观察与调整",guideStep2Text:"任务会先被拆成贴合目标的阶段，再逐步显现。展开阶段可检查过程，也可带着反馈从这里重新执行。",guideStep3:"接入新的能力",guideStep3Text:"在设置中选择远程 URL 或本地命令，填写服务商给出的信息，ClearAct 会保存并测试连接。",mcpRegistryHint:"官方服务注册表",mcpOfficialHint:"官方参考服务",mcpSmitheryHint:"社区 MCP 目录",mcpGlamaHint:"社区 MCP 目录",mcpSourceNote:"第三方服务并非天然可信，请核对发布者和所需权限。",guidePermissionTitle:"权限怎么选？",guidePermissionText:"默认“日常”会自动完成读取和工作区文件修改；外部写入、工作区外写入及破坏性操作仍会先询问。",gotIt:"知道了",connected:"本地网关已连接",placeholder:"告诉 ClearAct 你希望完成什么…",workspace:"工作区",workspaceChanged:"工作区已切换",send:"发送",stop:"停止运行",language:"界面语言",maxIterations:"最大迭代",maxTools:"最大工具调用",defaultProfile:"默认 Profile",save:"保存配置",cancel:"取消",confirm:"确定",rename:"重命名",delete:"删除",user:"你",running:"运行中",completed:"已完成",failed:"失败",cancelled:"已停止",created:"准备中",waiting_approval:"等待确认",reasoning:"模型公开说明",reasoningHint:"这里仅展示模型/API 明确返回的公开内容，不尝试还原隐藏思维链。",feedbackHint:"说明你希望怎样调整；将保留此前已完成阶段",restart:"从此阶段重新执行",searches:"检索记录",pages:"已访问网页",files:"文件操作",noSources:"尚无可打开的来源。",success:"成功",denied:"被策略阻止",failedAction:"操作失败",approvalTitle:"确认操作",approveAction:"允许",denyAction:"拒绝"},
  en: {newTopic:"New topic",history:"History",settings:"Settings",settingsHint:"Permissions, models & extensions",guide:"User guide",guideHint:"Start here",welcomeTitle:"Tell me the goal. ClearAct handles the rest.",welcomeHint:"Describe the outcome and ClearAct will use files, web research, and connected MCP capabilities as needed.",exampleFiles:"Work with files",exampleFilesHint:"Choose a folder, then read, analyze, or create files",exampleMcp:"Connect a capability",exampleMcpHint:"Choose a connection and ClearAct configures it",openGuide:"Open guide",guideStep1:"Describe the goal",guideStep1Text:"Use natural language in the composer.",guideStep2:"Observe and adjust",guideStep2Text:"The task is split into specific phases that appear as work begins. Inspect or restart any phase with feedback.",guideStep3:"Connect capabilities",guideStep3Text:"Choose a remote URL or local command in Settings; ClearAct saves and tests it.",mcpRegistryHint:"Official registry",mcpOfficialHint:"Official reference servers",mcpSmitheryHint:"Community MCP directory",mcpGlamaHint:"Community MCP directory",mcpSourceNote:"Verify third-party publishers and requested permissions.",guidePermissionTitle:"Which permissions?",guidePermissionText:"Balanced mode automates reads and workspace edits while asking before external writes and destructive work.",gotIt:"Got it",connected:"Local gateway connected",placeholder:"Tell ClearAct what to do…",workspace:"Workspace",workspaceChanged:"Workspace changed",send:"Send",stop:"Stop",language:"Language",maxIterations:"Max iterations",maxTools:"Max tool calls",defaultProfile:"Default profile",save:"Save",cancel:"Cancel",confirm:"Confirm",rename:"Rename",delete:"Delete",user:"You",running:"Running",completed:"Completed",failed:"Failed",cancelled:"Stopped",created:"Ready",waiting_approval:"Awaiting approval",reasoning:"Model explanation",reasoningHint:"Only explicit model/API output is shown; hidden chain-of-thought is not reconstructed.",feedbackHint:"Describe the change; completed earlier phases will be reused",restart:"Restart from this phase",searches:"Searches",pages:"Visited pages",files:"File operations",noSources:"No sources yet.",success:"Succeeded",denied:"Blocked by policy",failedAction:"Failed",approvalTitle:"Approve action",approveAction:"Allow",denyAction:"Deny"}
};

const t = (key) => text[language]?.[key] || key;
const escape = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function safeHttpUrl(value) { try { const url = new URL(String(value)); return ["http:", "https:"].includes(url.protocol) ? url.href : ""; } catch { return ""; } }
async function json(url, options) { const response = await fetch(url, options); const body = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(body?.detail || "Request failed"); return body; }
function applyLanguage() { document.documentElement.lang = language === "zh" ? "zh-CN" : "en"; document.querySelectorAll("[data-i18n]").forEach((node) => node.textContent = t(node.dataset.i18n)); document.querySelectorAll("[data-i18n-placeholder]").forEach((node) => node.placeholder = t(node.dataset.i18nPlaceholder)); }
function setWorkspace(path) { const effective = path || config?.default_workdir || ""; selectedWorkdir = effective || null; $("#workspace-path").textContent = effective; $("#workspace-indicator").title = effective ? `${t("workspace")}: ${effective}` : t("workspace"); }
function profileOptions(selected) { return config.profiles.map((profile) => `<option value="${escape(profile)}" ${profile === selected ? "selected" : ""}>${escape(profile)}</option>`).join(""); }
async function loadConfig() { config = await json("/api/config"); language = config.interface_language || "zh"; applyLanguage(); setWorkspace(config.default_workdir); }

async function loadRuns() {
  const runs = await json("/api/runs");
  $("#run-count").textContent = runs.length;
  $("#runs").innerHTML = runs.length ? runs.map((run) => `<div class="topic-row"><button class="topic ${run.id === activeId ? "active" : ""}" data-id="${escape(run.id)}"><div class="topic-goal">${escape(run.title)}</div><div class="topic-meta"><span>${new Date(run.updated_at).toLocaleDateString()}</span><span class="badge status-${escape(run.status)}">${t(run.status)}</span></div></button><button class="topic-menu" data-id="${escape(run.id)}">⋯</button></div>`).join("") : `<p class="muted">${language === "zh" ? "尚无过往话题。" : "No topics yet."}</p>`;
  document.querySelectorAll(".topic").forEach((node) => node.onclick = () => showRun(node.dataset.id));
  document.querySelectorAll(".topic-menu").forEach((node) => node.onclick = () => { const run = runs.find((item) => item.id === node.dataset.id); openTopicMenu(run.id, run.title); });
}

function markdown(value) {
  let output = escape(value || "");
  output = output.replace(/^### (.+)$/gm,"<h4>$1</h4>").replace(/^## (.+)$/gm,"<h3>$1</h3>").replace(/^# (.+)$/gm,"<h2>$1</h2>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/^[-*] (.+)$/gm,"<li>$1</li>").replace(/(?:<li>.*<\/li>\n?)+/g,(match) => `<ul>${match}</ul>`).replace(/\n\n/g,"</p><p>").replace(/\n/g,"<br>");
  return `<p>${output}</p>`;
}
function resultMap(detail) { return new Map(detail.run.messages.filter((message) => message.role === "tool" && message.tool_call_id).map((message) => [message.tool_call_id, message])); }
function workflowData(detail) {
  const calls = [];
  detail.run.messages.forEach((message, messageIndex) => message.tool_calls?.filter((action) => !["declare_workflow_plan", "declare_workflow_step"].includes(action.tool_name)).forEach((action) => calls.push({...action, messageIndex})));
  return {steps: detail.run.workflow_steps || [], calls};
}
function actionStatus(result) { const status = result?.metadata?.status; if (status === "succeeded") return t("success"); if (status === "denied") return t("denied"); if (["failed","cancelled"].includes(status)) return `${t("failedAction")}：${escape(result?.metadata?.error || result?.content || "")}`; return language === "zh" ? "进行中" : "In progress"; }
function reasoningHtml(detail, step) { const ids = new Set(step.action_ids || []); const reasoning = detail.run.messages.filter((message) => message.role === "assistant" && message.reasoning_content?.trim() && message.tool_calls?.some((action) => ids.has(action.id))).map((message) => message.reasoning_content.trim()); return reasoning.length ? `<details class="reasoning-details"><summary>${t("reasoning")}<span>${language === "zh" ? "展开" : "Expand"}</span></summary><div class="reasoning-content"><p class="reasoning-hint">${t("reasoningHint")}</p>${reasoning.map(markdown).join("")}</div></details>` : ""; }
function researchLayout(detail, actions) {
  const results = resultMap(detail), searches = actions.filter((action) => action.tool_name === "web_search"), pages = actions.filter((action) => action.tool_name === "fetch_url");
  if (!searches.length && !pages.length) return "";
  const searchHtml = searches.map((action) => { const result = results.get(action.id); const urls = [...(result?.content || "").matchAll(/https?:\/\/[^\s)]+/g)].map((match) => match[0]); return `<section class="action-record"><div><b>${escape(action.arguments?.query || "")}</b><small>${actionStatus(result)}</small></div><div class="source-links">${urls.map((value) => { const url = safeHttpUrl(value); return url ? `<a href="${escape(url)}" target="_blank" rel="noopener">${escape(value)}</a>` : ""; }).join("") || `<span class="muted">${t("noSources")}</span>`}</div></section>`; }).join("");
  const pageHtml = pages.map((action) => { const result = results.get(action.id), value = action.arguments?.url || "", url = safeHttpUrl(value); return `<section class="action-record"><div>${url ? `<a href="${escape(url)}" target="_blank" rel="noopener">${escape(value)}</a>` : escape(value)}<small>${actionStatus(result)}</small></div></section>`; }).join("");
  return `<div class="research-layout">${searchHtml ? `<h4>${t("searches")}</h4>${searchHtml}` : ""}${pageHtml ? `<h4>${t("pages")}</h4>${pageHtml}` : ""}</div>`;
}
function actionLayout(detail, actions) {
  const results = resultMap(detail), ordinary = actions.filter((action) => !["web_search","fetch_url"].includes(action.tool_name));
  if (!ordinary.length) return "";
  return `<div class="action-layout"><h4>${t("files")}</h4>${ordinary.map((action) => { const result = results.get(action.id), target = result?.metadata?.path || action.arguments?.path || action.arguments?.url || ""; return `<section class="action-record"><div><b>${escape(action.tool_name.replace(/^mcp__/, ""))}</b><small>${actionStatus(result)}</small></div>${target ? `<p>${escape(target)}</p>` : ""}</section>`; }).join("")}</div>`;
}
function planHtml(run) {
  if (!run.workflow_plan?.length) return `<div class="plan-loading"><i></i>${language === "zh" ? "正在生成与任务匹配的步骤…" : "Creating a task-specific plan…"}</div>`;
  const reached = new Set((run.workflow_steps || []).map((step) => step.plan_item_id));
  return `<ol class="workflow-plan">${run.workflow_plan.map((item) => `<li class="${reached.has(item.id) ? "reached" : ""}"><span></span><div><b>${escape(item.title)}</b><p>${escape(item.summary)}</p></div></li>`).join("")}</ol>`;
}
function stepCard(detail, step, calls, index) {
  const actions = (step.action_ids || []).map((id) => calls.find((call) => call.id === id)).filter(Boolean);
  const isUnderstand = step.id === "understand";
  const specialized = isUnderstand ? planHtml(detail.run) : researchLayout(detail, actions) + actionLayout(detail, actions);
  const canRestart = !["created","running","waiting_approval","paused"].includes(detail.run.status);
  const open = openStepDetails.has(step.id) ? " open" : "";
  return `<article class="message stage-message" data-step-id="${escape(step.id)}"><div class="stage-rail"><span class="stage-index">${String(index + 1).padStart(2,"0")}</span><i class="stage-dot ${escape(step.status || "completed")}"></i></div><section class="stage-card"><div class="stage-title"><h3>${escape(step.title)}</h3><span class="step-status">${t(step.status || "completed")}</span></div><details class="stage-details"${open}><summary>${escape(step.summary)}<span>${language === "zh" ? "查看详情" : "Details"}</span></summary><div class="stage-expanded">${specialized || `<p class="process-label">${escape(step.summary)}</p>`}${reasoningHtml(detail, step)}<form class="stage-feedback"><textarea placeholder="${escape(t("feedbackHint"))}"></textarea><button class="secondary-button" type="submit" ${canRestart ? "" : "disabled"}>${t("restart")}</button></form></div></details></section></article>`;
}
function revisionHtml(run) { const revision = run.workflow_revisions?.at(-1); if (!revision) return ""; const count = revision.reused_step_ids?.length || 0, restored = revision.restored_snapshot_ids?.length || 0, warning = revision.rollback_warnings?.length ? (language === "zh" ? "；部分外部操作无法自动撤销" : "; some external effects could not be undone") : ""; return `<div class="revision-banner">↺ ${language === "zh" ? `已按反馈创建新分支，复用 ${count} 个前置阶段，恢复 ${restored} 个文件快照` : `New branch; reused ${count} phases and restored ${restored} file snapshots`}${warning}<small>${escape(revision.feedback || "")}</small></div>`; }
function connectionHtml(detail) { const event = [...(detail.events || [])].reverse().find((item) => ["model.retrying","model.recovered"].includes(item.type)); if (event?.type !== "model.retrying" || !["created","running"].includes(detail.run.status)) return ""; const attempt = event.data?.attempt || 2, total = event.data?.max_attempts || 3; return `<div class="connection-banner"><i></i><div><b>${escape(event.title)}</b><small>${escape(event.detail || "")} · ${language === "zh" ? `第 ${attempt}/${total} 次尝试` : `attempt ${attempt}/${total}`}</small></div></div>`; }
function deliverCard(detail) { const final = [...detail.run.messages].reverse().find((message) => message.role === "assistant" && !message.tool_calls?.length); if (!final && ["created","running","waiting_approval","paused"].includes(detail.run.status)) return ""; return `<article class="message stage-message result-card"><div class="stage-rail"><span class="stage-index">✓</span></div><section class="stage-card"><div class="stage-title"><h3>${language === "zh" ? "结果" : "Result"}</h3></div><div class="stage-direct">${final ? markdown(final.content) : `<p class="muted">${language === "zh" ? "任务没有生成最终答复。" : "No final response."}</p>`}</div>${final ? '<span class="copy-response-slot"></span>' : ""}</section></article>`; }

async function restartAtStage(stepId, feedback) { const result = await json("/api/runs", {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({goal:feedback, run_id:activeId, rewind_step_id:stepId, interface_language:language})}); lastRunSignature = null; await showRun(result.run_id); }
function renderRun(detail, {force = false} = {}) {
  const signature = JSON.stringify([detail.run.updated_at, detail.run.status, detail.run.messages.length, detail.events.length, detail.approval?.action_id, detail.run.workflow_steps, detail.run.workflow_plan]);
  $("#topic-title").textContent = detail.run.title || detail.run.goal.slice(0,48);
  $("#stop-run").classList.toggle("hidden", !["created","running","waiting_approval","paused"].includes(detail.run.status));
  $("#empty-state").classList.add("hidden"); $("#conversation").classList.remove("hidden"); syncApproval(detail);
  if (!force && signature === lastRunSignature) return;
  document.querySelectorAll(".stage-details[open]").forEach((node) => openStepDetails.add(node.closest("[data-step-id]")?.dataset.stepId));
  const {steps, calls} = workflowData(detail); const firstUser = detail.run.messages.find((message) => message.role === "user");
  $("#detail").innerHTML = `${firstUser ? `<article class="message role-user"><b>${t("user")}</b><div class="markdown">${markdown(firstUser.content)}</div></article>` : ""}${revisionHtml(detail.run)}${connectionHtml(detail)}${steps.map((step,index) => stepCard(detail,step,calls,index)).join("")}${deliverCard(detail)}`;
  document.querySelectorAll(".stage-details").forEach((node) => node.ontoggle = () => { const id = node.closest("[data-step-id]").dataset.stepId; node.open ? openStepDetails.add(id) : openStepDetails.delete(id); });
  document.querySelectorAll(".stage-feedback").forEach((form) => form.onsubmit = async (event) => { event.preventDefault(); const feedback = form.querySelector("textarea").value.trim(); const stepId = form.closest("[data-step-id]").dataset.stepId; if (!feedback) return; try { await restartAtStage(stepId, feedback); } catch (error) { $("#feedback").textContent = error.message; } });
  const final = [...detail.run.messages].reverse().find((message) => message.role === "assistant" && !message.tool_calls?.length), slot = $("#detail .copy-response-slot");
  if (slot && final?.content) { const button = document.createElement("button"); button.className = "copy-response secondary-button"; button.type = "button"; button.dataset.copy=final.content; button.textContent = language === "zh" ? "复制答复" : "Copy"; button.onclick = async () => { await navigator.clipboard.writeText(button.dataset.copy); button.textContent = language === "zh" ? "已复制" : "Copied"; }; slot.replaceWith(button); }
  lastRunSignature = signature;
}

function syncApproval(detail) { const dialog = $("#approval-dialog"), approval = detail.approval; if (!approval) { if (dialog.open) dialog.close(); return; } dialog.dataset.runId = detail.run.id; dialog.dataset.actionId = approval.action_id; $("#approval-summary").textContent = `${approval.tool_name} · ${approval.risk}\n${(approval.reasons || []).join("\n")}`; $("#approval-arguments").textContent = JSON.stringify(approval.arguments || {}, null, 2); if (!dialog.open) dialog.showModal(); }
async function submitApproval(approved) { const dialog = $("#approval-dialog"); await json(`/api/runs/${dialog.dataset.runId}/approval`, {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({action_id:dialog.dataset.actionId, approved})}); dialog.close(); await showRun(dialog.dataset.runId); }
async function showRun(id, {force = true} = {}) { activeId = id; const detail = await json(`/api/runs/${id}`); setWorkspace(detail.run.execution?.workdir); renderRun(detail, {force}); await loadRuns(); }
function newTopic() { activeId = null; lastRunSignature = null; setWorkspace(config?.default_workdir); $("#stop-run").classList.add("hidden"); $("#topic-title").textContent = t("newTopic"); $("#conversation").classList.add("hidden"); $("#empty-state").classList.remove("hidden"); $("#goal").focus(); loadRuns(); }

let topicAction = null;
function openTopicMenu(id,title) { topicAction = {id, mode:"rename"}; $("#topic-dialog-title").textContent = `${t("rename")} / ${t("delete")}`; $("#topic-input").value = title; $("#topic-input").classList.remove("hidden"); $("#topic-delete-warning").classList.add("hidden"); $("#topic-delete").classList.remove("hidden"); $("#topic-delete").onclick = () => { topicAction.mode = "delete"; $("#topic-delete-warning").classList.remove("hidden"); $("#topic-input").classList.add("hidden"); $("#topic-delete").classList.add("hidden"); }; $("#topic-dialog").showModal(); }

const capabilityMeta = [
  ["local_read","读取本地文件","查看已授权目录中的内容"],["web_read","联网查资料","搜索和读取公开网页"],["workspace_create","创建文件","在工作区生成新文件"],["workspace_modify","修改文件","更新工作区已有文件"],["mcp_read","MCP 只读","调用服务声明为只读的工具"],["mcp_write","MCP 外部操作","调用可能改变外部状态的工具"],["outside_write","工作区外写入","修改本次工作目录之外的文件"],["destructive","高影响操作","删除、发布或服务声明的破坏性动作"]
];
const presets = {
  cautious:{local_read:"allow",web_read:"allow",workspace_create:"ask",workspace_modify:"ask",mcp_read:"ask",mcp_write:"ask",outside_write:"ask",destructive:"ask",other:"ask"},
  balanced:{local_read:"allow",web_read:"allow",workspace_create:"allow",workspace_modify:"allow",mcp_read:"allow",mcp_write:"ask",outside_write:"ask",destructive:"ask",other:"ask"},
  trusted:{local_read:"allow",web_read:"allow",workspace_create:"allow",workspace_modify:"allow",mcp_read:"allow",mcp_write:"allow",outside_write:"allow",destructive:"ask",other:"allow"}
};
function renderCapabilityRules(rules) { $("#capability-rules").innerHTML = capabilityMeta.map(([key,title,hint]) => `<div class="capability-row"><div><b>${title}</b><small>${hint}</small></div><select data-capability="${key}">${key === "destructive" ? "" : `<option value="allow" ${rules[key] === "allow" ? "selected" : ""}>自动执行</option>`}<option value="ask" ${rules[key] === "ask" ? "selected" : ""}>先询问</option><option value="deny" ${rules[key] === "deny" ? "selected" : ""}>关闭</option></select></div>`).join(""); }
function currentCapabilityRules() { const rules = {}; document.querySelectorAll("[data-capability]").forEach((node) => rules[node.dataset.capability] = node.value); rules.other = settings?.capability_rules?.other || "ask"; return rules; }
function syncProfileProvider(card) { const provider = card.querySelector('[data-key="provider"]').value, hint = card.querySelector(".profile-hint"); hint.textContent = provider === "ollama" ? (language === "zh" ? "Ollama 原生接口：Base URL 通常为 http://localhost:11434，程序调用 /api/chat。" : "Native Ollama: the Base URL is usually http://localhost:11434; ClearAct calls /api/chat.") : (language === "zh" ? "OpenAI 兼容接口：Base URL 应包含 /v1，程序调用 /chat/completions。" : "OpenAI-compatible: include /v1 in the Base URL; ClearAct calls /chat/completions."); }
function renderProfileSettings() { const root = $("#profile-settings"); root.replaceChildren(); Object.entries(settings.profiles || {}).forEach(([name,profile]) => { const card = document.createElement("div"); card.className = "profile-card"; card.dataset.profile = name; card.innerHTML = `<strong>${escape(name)}</strong><label>接口类型<select data-key="provider"><option value="ollama">Ollama 原生（/api/chat）</option><option value="openai_compatible">OpenAI 兼容（/v1/chat/completions）</option></select></label><label>Model<input data-key="model"></label><small class="profile-hint span-two"></small><label>Base URL<input data-key="baseUrl"></label><label>Context<input data-key="contextWindow" type="number"></label><label class="span-two">API Key<input data-key="apiKey" type="password"></label>`; Object.entries({provider:"provider",model:"model",baseUrl:"baseUrl",contextWindow:"contextWindow"}).forEach(([key]) => card.querySelector(`[data-key="${key}"]`).value = profile[key] ?? ""); card.querySelector('[data-key="provider"]').onchange = () => syncProfileProvider(card); card.querySelector('[data-key="apiKey"]').placeholder = profile.hasApiKey ? "已设置，留空保持不变" : "留空表示不设置"; syncProfileProvider(card); root.appendChild(card); }); }
function renderMcpServers() { const entries = Object.entries(settings.mcp_servers || {}); $("#mcp-server-list").innerHTML = entries.length ? entries.map(([name,server]) => `<article class="mcp-server-card"><span class="connection-dot ${server.enabled === false ? "off" : ""}"></span><div><b>${escape(name)}</b><small>${escape(server.url || server.command || "")}</small></div><label class="mini-toggle"><input type="checkbox" data-mcp-toggle="${escape(name)}" ${server.enabled === false ? "" : "checked"}>启用</label><button type="button" data-mcp-test="${escape(name)}">测试</button><button type="button" data-mcp-edit="${escape(name)}">编辑</button><button type="button" data-mcp-delete="${escape(name)}">删除</button></article>`).join("") : `<div class="empty-extension">还没有 MCP 服务。点击“添加服务”即可开始。</div>`; bindMcpActions(); }
function bindMcpActions() { document.querySelectorAll("[data-mcp-toggle]").forEach((node) => node.onchange = async () => { await json(`/api/mcp/servers/${encodeURIComponent(node.dataset.mcpToggle)}/enabled?enabled=${node.checked}`, {method:"PUT"}); await refreshSettings(); }); document.querySelectorAll("[data-mcp-test]").forEach((node) => node.onclick = () => testMcp(node.dataset.mcpTest)); document.querySelectorAll("[data-mcp-edit]").forEach((node) => node.onclick = () => openMcpEditor(node.dataset.mcpEdit)); document.querySelectorAll("[data-mcp-delete]").forEach((node) => node.onclick = async () => { if (!confirm(`删除 MCP 服务 ${node.dataset.mcpDelete}？`)) return; await json(`/api/mcp/servers/${encodeURIComponent(node.dataset.mcpDelete)}`, {method:"DELETE"}); await refreshSettings(); }); }
async function refreshSettings() { settings = await json("/api/settings"); renderMcpServers(); }
function openMcpEditor(name = null) { editingMcpName = name; const server = name ? settings.mcp_servers[name] : {}; $("#mcp-name").value = name || ""; $("#mcp-name").disabled = Boolean(name); $("#mcp-transport").value = server.transport || (server.url ? "streamable_http" : "streamable_http"); $("#mcp-url").value = server.url || ""; $("#mcp-command").value = server.command || ""; $("#mcp-args").value = (server.args || []).join(" "); $("#mcp-secret-name").value = server.headerKeys?.[0] || server.envKeys?.[0] || ""; $("#mcp-secret-kind").value = server.envKeys?.length ? "env" : "header"; $("#mcp-secret-value").value = ""; $("#mcp-editor").classList.remove("hidden"); syncMcpTransport(); }
function syncMcpTransport() { const local = $("#mcp-transport").value === "stdio"; document.querySelectorAll(".mcp-stdio-field").forEach((node) => node.classList.toggle("hidden", !local)); document.querySelectorAll(".mcp-http-field").forEach((node) => node.classList.toggle("hidden", local)); }
function splitArgs(value) { return [...value.matchAll(/"([^"]*)"|'([^']*)'|([^\s]+)/g)].map((match) => match[1] ?? match[2] ?? match[3]); }
async function testMcp(name) { const note = $("#mcp-feedback"); note.textContent = `正在测试 ${name}…`; try { const result = await json(`/api/mcp/servers/${encodeURIComponent(name)}/test`, {method:"POST"}); note.textContent = `连接成功，发现 ${result.tools.length} 个工具`; } catch (error) { note.textContent = `连接失败：${error.message}`; } }
async function saveMcp() { const body = {name:editingMcpName || $("#mcp-name").value.trim(), transport:$("#mcp-transport").value, url:$("#mcp-url").value.trim() || null, command:$("#mcp-command").value.trim() || null, args:splitArgs($("#mcp-args").value), secret_kind:$("#mcp-secret-kind").value, secret_name:$("#mcp-secret-name").value.trim() || null, secret_value:$("#mcp-secret-value").value || null, enabled:true}; const result = await json("/api/mcp/servers", {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(body)}); $("#mcp-editor").classList.add("hidden"); await refreshSettings(); await testMcp(body.name); return result; }

async function openSettings() { settings = await json("/api/settings"); $("#interface-language").value = settings.interface_language || "zh"; $("#default-autonomy").value = settings.default_autonomy || "yellow"; $("#default-iterations").value = settings.max_iterations; $("#default-tool-calls").value = settings.max_tool_calls; $("#default-profile").innerHTML = profileOptions(settings.default_profile); renderCapabilityRules({...presets.balanced,...settings.capability_rules}); renderProfileSettings(); renderMcpServers(); $("#settings-dialog").showModal(); }

$("#grant-approval").onclick = () => submitApproval(true); $("#deny-approval").onclick = () => submitApproval(false);
$("#stop-run").onclick = async () => { if (activeId) { await json(`/api/runs/${activeId}/stop`, {method:"POST"}); await showRun(activeId); } };
$("#guide-trigger").onclick = () => $("#guide-dialog").showModal(); $("#welcome-guide").onclick = () => $("#guide-dialog").showModal();
async function chooseWorkdir() { try { const result = await json("/api/select-directory", {method:"POST"}); if (result.path) { setWorkspace(result.path); $("#feedback").textContent = t("workspaceChanged"); $("#goal").focus(); } } catch (error) { $("#feedback").textContent = error.message; } }
$("#choose-workdir").onclick = chooseWorkdir;
$("#workspace-indicator").onclick = chooseWorkdir;
$("#open-mcp-quick").onclick = async () => { await openSettings(); openMcpEditor(); $("#mcp-settings").scrollIntoView({behavior:"smooth"}); };
$("#new-topic").onclick = newTopic; $("#settings-trigger").onclick = openSettings; $("#save-settings-button").onclick = () => $("#settings-form").requestSubmit();
$("#add-mcp-button").onclick = () => openMcpEditor(); $("#cancel-mcp-button").onclick = () => $("#mcp-editor").classList.add("hidden"); $("#mcp-transport").onchange = syncMcpTransport; $("#save-mcp-button").onclick = async () => { try { await saveMcp(); } catch (error) { $("#mcp-feedback").textContent = error.message; } };
document.querySelectorAll("[data-preset]").forEach((button) => button.onclick = () => { renderCapabilityRules(presets[button.dataset.preset]); document.querySelectorAll("[data-preset]").forEach((item) => item.classList.toggle("active", item === button)); });
document.querySelectorAll("[data-close]").forEach((button) => button.onclick = () => $("#" + button.dataset.close).close());
document.addEventListener("keydown", (event) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); newTopic(); } });
$("#goal").addEventListener("keydown", (event) => { if (event.key === "Enter" && !event.shiftKey && !event.isComposing) { event.preventDefault(); $("#run-form").requestSubmit(); } });
$("#topic-form").onsubmit = async (event) => { event.preventDefault(); if (topicAction.mode === "delete") await json(`/api/runs/${topicAction.id}`, {method:"DELETE"}); else await json(`/api/runs/${topicAction.id}`, {method:"PUT", headers:{"Content-Type":"application/json"}, body:JSON.stringify({title:$("#topic-input").value.trim()})}); $("#topic-dialog").close(); activeId === topicAction.id ? await showRun(activeId) : await loadRuns(); };
$("#run-form").onsubmit = async (event) => { event.preventDefault(); const goal = $("#goal").value.trim(); if (!goal) return; try { const result = await json("/api/runs", {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({goal,run_id:activeId,interface_language:language,workdir:selectedWorkdir})}); activeId = result.run_id; $("#goal").value = ""; await showRun(activeId); } catch (error) { $("#feedback").textContent = error.message; } };
$("#settings-form").onsubmit = async (event) => { event.preventDefault(); const profiles = {}; document.querySelectorAll(".profile-card").forEach((card) => { const profile = {}; card.querySelectorAll("[data-key]").forEach((input) => { if (input.dataset.key === "apiKey" && !input.value.trim()) return; profile[input.dataset.key] = input.type === "number" ? Number(input.value) : input.value.trim(); }); profiles[card.dataset.profile] = profile; }); try { await json("/api/settings", {method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({interface_language:$("#interface-language").value,default_autonomy:$("#default-autonomy").value,max_iterations:Number($("#default-iterations").value),max_tool_calls:Number($("#default-tool-calls").value),default_profile:$("#default-profile").value,profiles,capability_rules:currentCapabilityRules()})}); $("#settings-feedback").textContent = language === "zh" ? "已保存" : "Saved"; } catch (error) { $("#settings-feedback").textContent = error.message; } };
$("#mcp-import-button").onclick = async () => { try { const result = await json("/api/mcp/import", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({config:JSON.parse($("#mcp-import").value)})}); $("#mcp-feedback").textContent = `已导入：${result.imported.join(", ")}`; $("#mcp-import").value = ""; await refreshSettings(); } catch (error) { $("#mcp-feedback").textContent = error.message; } };

let pollBusy = false;
(async () => {
  await loadConfig();
  await loadRuns();
  setInterval(async () => {
    if (!activeId || pollBusy) return;
    pollBusy = true;
    try { renderRun(await json(`/api/runs/${activeId}`)); } finally { pollBusy = false; }
  }, 1000);
  setInterval(() => loadRuns().catch(() => {}), 8000);
})().catch((error) => $("#feedback").textContent = error.message);
